global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
# scrape_configs:
# - job_name: prometheus
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - localhost:9090
# - job_name: 'promswarmconnect'
#   relabel_configs:
#   - source_labels: [__meta_triton_machine_image]
#     target_label: job
#   - source_labels: [__meta_triton_machine_id]
#     target_label: instance
#   - source_labels: [__meta_triton_machine_alias]
#     target_label: __address__
#   - source_labels: [__meta_triton_server_id]
#     target_label: __metrics_path__
#   triton_sd_configs:
#   - account: 'dummyaccount'
#     dns_suffix: 'dummy' # required
#     endpoint: 'promswarmconnect'
#     port: 443
#     refresh_interval: 15s
#     version: 1
#     tls_config:
#       insecure_skip_verify: true

scrape_configs:
  - job_name: swarm-service-endpoints
    file_sd_configs:
      - files:
        - /etc/swarm-endpoints/swarm-endpoints.json
    relabel_configs:
      # Set the instance to the hostname
      - source_labels: [__meta_swarm_node_hostname]
        target_label: instance
      # scrap only running tasks  
      - source_labels: [__meta_swarm_task_desired_state]
        regex: running
        action: keep
      # Add a task label
      - source_labels: [__meta_swarm_task_name]
        target_label: task